import styles from "./layout.module.scss";
import "./../styles/global.scss";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { Sidenav } from "@components/sidenav/sidenav";
config.autoAddCss = false;

export const metadata = {
  title: "Bytebank",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={styles.custom_body}>
        <Sidenav />
        <div className={styles.content}>{children}</div>
      </body>
    </html>
  );
}
